# Copyright (c) 2023-2024 Microbus LLC and various contributors
# 
# This file and the project encapsulating it are the confidential intellectual property of Microbus LLC.
# Neither may be used, copied or distributed without the express written consent of Microbus LLC.

hello.example:
  Repeat: 3
  Greeting: Ciao

http.ingress.sys:
#  Ports: 8080
#  TimeBudget: 20s

inbox.sys:
  Host: cc.selgine.com

# all:
#   Maria: "root:secret1234@tcp(127.0.0.1:3306)/microbus_examples_shard%d"
