name: "Test"
on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
      - uses: actions/checkout@v3
      - name: Create Nats cluster
        uses: onichandame/nats-action@master
        with:
          port: 4222
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: "Show version"
        run: go version
      - name: "Run tests"
        run: go test ./...
